AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handler
      Runtime: go1.x
Outputs:
  ServiceToken:
    Value: !GetAtt Function.Arn
